[project]
name = "mod3-project2-nlp-group2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datasets>=5.0.1",
    "datetime>=6.0",
    "google-api-python-client>=2.200.0",
    "huggingface-hub>=1.31.0",
    "kagglehub>=1.0.2",
    "numpy>=2.5.3",
    "pandas>=3.0.5",
    "polars>=1.44.2",
    "python-dotenv>=1.2.3",
    "safetensors>=0.8.0",
    "scikit-learn>=1.9.1",
    "torch>=2.14.0",
    "transformers>=5.17.0",
]
